### PR TITLE
Fixed empty responseBody

### PR DESCRIPTION
**Pull request by fharzendorf**
Fixed an issue where disabling sourceopt would return an empty responseBody.

### CODE REVIEW

**Comment by lochmueller** [comment]
Great. Thanks for the PullRequest

**Comment by fharzendorf** [comment]
Maybe we should increase the version number in the ext_emconf.php?

**Comment by lochmueller** [comment]
I will raise the version on the next release.

**Comment by fharzendorf** [comment]
Thank you!

**Pull request merged**
